apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod #can be the same as the POD
      app: demo-voting-app

  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod #can be the same as the POD
        app: demo-voting-app #nane if the application, all PODs will have these, hence group them
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432 #defaul
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
