apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod #can be the same as the POD
    app: demo-voting-app #nane if the application, all PODs will have these, hence group them
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432 #defaul
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust

#So as we saw in the previous lecture, the source code of the worker and the 
#result pod has the password for the post PostgreSQL database hardcoded in them.
