apiVersion: v1 
kind: Service
metadata:
  name: db # worker app has hardcoded db as the name so it expects it, doesnt teh vote app too?
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector: #So in order to link the service to the port, we must specify the same labels configured for the POD.
    name: postgres-pod
    app: demo-voting-app