apiVersion: v1 
kind: Service
metadata:
  name: redis # this is important ,its hardcoded in other containers that reference it
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector: #So in order to link the service to the port, we must specify the same labels configured for the POD.
    name: redis-pod
    app: demo-voting-app