apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod #can be the same as the POD
    app: demo-voting-app #nane if the application, all PODs will have these, hence group them
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379