apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app-pod #can be the same as the POD
    app: demo-voting-app #nane of the application
spec:
  containers:
    - name: result-app-pod
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80 #So this should be the port on which the application listens for this voting app.

#This definition file is a copy of voting-app-pod.yaml with some name changes metadata: and image:
#Cuse the containers are both external facing