apiVersion: v1 
kind: Service
metadata:
  name: result-service 
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: #So in order to link the service to the port, we must specify the same labels configured for the POD. (same labels in the POD definition file)
    name: result-app-pod
    app: demo-voting-app
