apiVersion: v1 
kind: Service
metadata:
  name: voting-service 
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort #default is ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: #So in order to link the service to the port, we must specify the same labels configured for the POD. (same labels in the POD definition file)
    name: voting-app-pod
    app: demo-voting-app